#spring.profiles.active=test,dev,custom
spring.application.name=example-prod
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=root
spring.datasource.password=123Change
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always


my.custom.property=general_configs
my.custom.property.int=32
