spring.application.name=example-test
server.port=8081

spring.datasource.url=jdbc:mariadb://localhost:3306/my_db
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.sql.init.mode=always


my.custom.property=it_is_coming_from_test
my.custom.property.int=9999
